export interface Tutor {
    membershipName: string,
    confirmerName: string,
    certificationUrls: string,
    averageRatingStar: number,
    numberOfCourse: number,
    numberOfTutee: number,
    numberOfFeedback: number,
    id: number,
    educationLevel: string,
    school: string,
    points: number,
    membershipId: number,
    socialIdUrl: string,
    confirmedBy: number,
    confirmedDate: string,
    createdDate: string,
    fullname: string,
    gender: string,
    birthday: string,
    email: string,
    phone: string,
    avatarImageLink: string,
    address: string,
    roleId: number,
    description: string,
    status: string
}